# Generated by Django 4.1.5 on 2023-01-27 02:04

from django.db import migrations, models
import teams.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('image', models.FileField(blank=True, null=True, upload_to=teams.models.team_image_file_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('completed_tasks_count', models.IntegerField(default=0)),
                ('notcompleted_tasks_count', models.IntegerField(default=0)),
            ],
        ),
    ]
